version: '3.1'
services:
  db:
    image: postgres:14.1
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SNF_BOT_DB_PASS}
  adminer:
    image: adminer
    ports:
      - 127.0.0.1:8080:8080
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - 8443:8443
    depends_on:
      - db
    entrypoint: '/usr/app/wait-for-it.sh ${SNF_BOT_DB_HOST}:5432 --'
    command: ['python3', 'src/python/app.py']
